export const STATUS: Record<string, { label: string; badge: string; dot: string; num: string; cardBg: string; hl: string; bar: string }> = {
  supported: {
    label: 'Supported',
    badge: 'bg-[#DCFCE7] text-[#15803D] border-[#BBF7D0]',
    dot: 'bg-[#16A34A]',
    num: 'text-[#16A34A]',
    cardBg: 'bg-[#F0FDF4]',
    hl: 'bg-[#DCFCE7] text-slate-900',
    bar: 'bg-[#22C55E]',
  },
  uncertain: {
    label: 'Uncertain',
    badge: 'bg-[#FEF3C7] text-[#B45309] border-[#FDE68A]',
    dot: 'bg-[#D97706]',
    num: 'text-[#D97706]',
    cardBg: 'bg-[#FFFBEB]',
    hl: 'bg-[#FEF3C7] text-slate-900',
    bar: 'bg-[#F59E0B]',
  },
  unsupported: {
    label: 'Unsupported',
    badge: 'bg-[#FEE2E2] text-[#B91C1C] border-[#FECACA]',
    dot: 'bg-[#EF4444]',
    num: 'text-[#EF4444]',
    cardBg: 'bg-[#FEF2F2]',
    hl: 'bg-[#FEE2E2] text-slate-900',
    bar: 'bg-[#EF4444]',
  },
  verifying: {
    label: 'Verifying...',
    badge: 'bg-slate-100 text-slate-600 border-slate-200',
    dot: 'bg-slate-400 animate-pulse',
    num: 'text-slate-500',
    cardBg: 'bg-slate-50',
    hl: 'bg-slate-100 text-slate-900',
    bar: 'bg-slate-300',
  },
};
